spring.application.name=${SPRING_APPLICATION_NAME:LMS}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/lmsjson?authSource=admin}
spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED:true}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:500MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:500MB}
app.reset-password.url=${APP_RESET_PASSWORD_URL:http://localhost:4200/new-password}
task.file.path=${TASK_FILE_PATH:uploads/}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}