spring.application.name=LMS
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=lmsjson
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
app.reset-password.url=http://localhost:4200/new-password


task.file.path=uploads/
#mailconfig
spring.mail.host=smtp.gmail.com
spring.mail.username=noreply@yourdomain.com
spring.mail.password=APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.port=587
#spring.web.resources.static-locations=classpath:/static/,file:./uploads/
